version: '2'
services:
  proxysql:
    image: proxysql/proxysql:2.0.8
    ports:
      - "6032:6032"
      - "6033:6033"
    volumes:
      - ./conf/proxysql.cnf:/etc/proxysql.cnf

  mysql:
    image: mysql:5.7
    ports:
      - "3316:3306"
    volumes:
      - ./conf/master.cnf:/etc/mysql/conf.d/my.cnf
      - ./conf/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"

  mysql-slave:
    image: mysql:5.7
    ports:
      - '3317:3306'
    depends_on:
      - mysql
    tmpfs: /var/lib/mysql
    volumes:
      - ./conf/slave.cnf:/etc/mysql/conf.d/my.cnf
      - ./conf/start-slave.sh:/docker-entrypoint-initdb.d/start-slave.sh
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
